### ISSUE TITLE
Check if GPU is necessary for prediction of labels

### ISSUE THREAD

**Issue by JesJehle** [Deadwood-ai/deadwood-api#20]

**Comment by cmosig** [comment]
yes, GPU is necessary for 
1) deadwood prediction in orthophotos
2) preprocess sentinel data iff we do that on our infa
3) prediction of deadwood data iff we do it on our infra

**Comment by mmaelicke** [comment]
Maybe we move this issue somewhere else, as this does not affect the storage server, right?

**Comment by cmosig** [comment]
yes, separate server. both from an application and hardware point of view
