### ISSUE TITLE
additional metadata files

### ISSUE THREAD

**Issue by JesJehle** [Deadwood-ai/deadwood-api#25]
- [ ] additional_information text (Damit Leute happy sind und ihre Forschungsprojekte nennen können.)

**Comment by cmosig** [comment]
Simple string, example: "'Data was acquiried during the project PYROPHOB funded by the Fachagentur Nachwachsende Rohstoffe e. V. (FNR), the Waldklimafonds, and the german Federal Ministries of Food and Agriculture (BMEL), and for the Environment, Nature Conservation, Nuclear Safety and Consumer Protection (BMUV)'"
