### ISSUE TITLE
AOI needs to be MultiPolygon

### ISSUE THREAD

**Issue by cmosig** [Deadwood-ai/deadwood-api#32]
We need support for MultiPolygons in the area of interest, i.e. same type as labels. Sometimes only selected parts of huge images were labeled.

**Comment by mmaelicke** [comment]
Will do that asap

**Comment by cmosig** [comment]
thanks!

**Comment by mmaelicke** [comment]
Should be a multipolygon now, on the `direct-cog` branch, not the main branch.

There is also a `verfiy_labels` function that gets called on each upload. Currently, that function just returns True. I was planning to check here, that the label are actually *within* the aoi. Does that make sense?

**Comment by cmosig** [comment]
Thanks!

 Sometimes are slightly outside the AOI. It may make sense to give a warning (not error) if the AOI or labels are outside the bounding box of the orthophoto. But that's only a nice to have, not strictly necessary.

**Comment by mmaelicke** [comment]
This is now also deployed on main channel with version `0.6.6` (which will be live later today).
