### ISSUE TITLE
Use a custom SMTP Server because superbase SMTP rate limit is too restrictive

### ISSUE THREAD

**Issue by JesJehle** [Deadwood-ai/deadwood-api#39]
As I understood in [#29 ](https://github.com/Deadwood-ai/deadwood-api/issues/29#issuecomment-2309730379) the current rate limit is 3 per hour. 
We also got a user who could not register:

>  I try to sign up but no confirmation was sent to me. 

I just tried to debug the registration process and got a rate limit error. 
Does this mean only 3 people could register in one hour? 
Superbase itself says that their SMTP Server is only for [development](https://supabase.com/docs/guides/auth/auth-smtp); hence, I think we should move to a custom provider instead, since the current limit would make the application unusable for a larger number of users.
They suggest:
* [Twilio SendGrid](https://docs.sendgrid.com/for-developers/sending-email/integrating-with-the-smtp-api)
* [AWS SES](https://docs.aws.amazon.com/ses/latest/dg/send-email-smtp.html)
* [Resend](https://resend.com/docs/dashboard/emails/introduction)

@mmaelicke @cmosig What do you think?

**Comment by mmaelicke** [comment]
This is bound to deadtrees.earth. I tried to set this up over my phone. Thus, you can try to increase the Limit. I can setup this properly after my vacation, if this does not yet work properly

**Comment by mmaelicke** [comment]
There is no need to pay another provider. I am already paying 1blu for the domain and smtp server

**Comment by JesJehle** [comment]
Awesome!
