### ISSUE TITLE
Error while querying OSM for admin level names

### ISSUE THREAD

**Issue by JesJehle** [Deadwood-ai/deadwood-api#43]
A lot of these:
```
[
  {
    "id": 7551,
    "created_at": "2024-09-06T11:44:12.368045+00:00",
    "name": "processor",
    "level": "ERROR",
    "message": "An error occurred while querying OSM for admin level names of dataset_id: 1238: Error: line 2: static error: For the attribute &quot;lat&quot; of the element &quot;coord-query&quot; the only allowed values are floats between -90.0 and 90.0. \nError: line 2: static error: For the attribute &quot;lon&quot; of the element &quot;coord-query&quot; the only allowed values are floats between -180.0 and 180.0. ",
    "origin": "upload.py",
```
from id: 1143 upwards.

**Comment by cmosig** [comment]
Looks like the query coords are off. Hmmm

**Comment by cmosig** [comment]
The issue is that there is no reprojection being done. Some orthophotos are in a CRS that is not EPSG:4326.

**Comment by cmosig** [comment]
As far as I remember, the consensus was that we store the incoming orthophotos in the CRS that we get it in for maximum accuracy and then reproject it to 4326 for the visualization.

**Comment by cmosig** [comment]
For the bounds, which is where the OSM query gets its data from, we need to change this line...

https://github.com/Deadwood-ai/deadwood-api/blob/e8a41af960c798abb0afe4c0ea0cf362a7cacbfc/src/routers/upload.py#L107C1-L107C28

...to `bounds = rasterio.warp.transform_bounds(src_crs=src.crs, dst_crs="EPSG:4326", *src.bounds)`


https://rasterio.readthedocs.io/en/latest/api/rasterio.warp.html#rasterio.warp.transform_bounds

**Comment by cmosig** [comment]
For the COGs, there does not seem to be a reprojection hapenning here:

https://github.com/Deadwood-ai/deadwood-api/blob/439d7cce8f5e2dcf0c4918429b798ea3c19ac0f3/src/deadwood/cog.py#L45

I think the correct flag is -t_crs=EPSG:4326

**Comment by JesJehle** [comment]
Perfect! We can rerun the process after the tiffs are imported.
