### ISSUE TITLE
unable to download because of rate limit exeeded

### ISSUE THREAD

**Issue by JesJehle** [Deadwood-ai/deadwood-api#47]
currently no download is possible. Example:
`https://data.deadtrees.earth/api/v1/download/datasets/2254/dataset.zip`

even just hitting:
`https://data.deadtrees.earth/api/v1/download/`
causes 
```
{"detail":"Rate limit exceeded. You can only download one file at a time."}
```

**Comment by mmaelicke** [comment]
I am not sure what is going wrong here. The download API seems to be mounted incorrectly, which doesn't make any sense as I was on vacation and had no chance to mess anything up.

Give me a few more tries to debug it, then we can still bypass the rate limit (which will potentially break the entire server...)
