### ISSUE TITLE
Download labels as gpkg

### ISSUE THREAD

**Issue by JesJehle** [Deadwood-ai/deadwood-api#52]

**Comment by mmaelicke** [comment]
Ich denke der label download funktioniert momentan nicht, da sich das Datenmodell geändert hat und diese Änderungen noch nicht in die download API nachgezogen ist. 

Oder was genau soll uns dieses issue mitteilen?

**Comment by JesJehle** [comment]
Der download funktioniert, da die meisten leute allerdings mit gpkg mehr anfangen können also mit json sollten wir das anpassen. Wollte ich nur festhalten.

**Comment by mmaelicke** [comment]
Aber der label download ist doch gpkg, oder nicht?

**Comment by JesJehle** [comment]
in ` @download_app.get("/datasets/{dataset_id}/dataset.zip")` wird es noch als json ausgegeben.

**Comment by mmaelicke** [comment]
Ok. Kann ich gerne ändern
