### ISSUE TITLE
Update License selection

### ISSUE THREAD

**Issue by JesJehle** [Deadwood-ai/deadwood-api#82]
Instead of the different available licenses offered at the moment:
* CC BY
* CC BY-SA
* CC BY-NC-SA
* MIT

Let's simplify the selection into:
### 1\. **Open Access**

-   **Description**: Data is fully accessible and downloadable.
-   **License**: CC BY
-   **Permissions**: Users can download, use, modify, and share your data with attribution.

### 2\. **View-Only Access**

-   **Description**: Data is visible on our platform but cannot be downloaded.
-   **License**: **Custom View-Only License**
-   **Permissions**:
    -   Users can view your data on our platform.
    -   Data cannot be downloaded or redistributed.
    -   We may use the data internally for training machine learning models.

### 3\. **Restricted Access**

-   **Description**: Data is not visualized; only its presence is indicated.
-   **License**: **All Rights Reserved**
-   **Permissions**: Data remains private and is not accessible to users.

**Note**: All data will be used to train our models to improve our services.

@cmosig @tejakattenborn What do you think?

**Comment by JesJehle** [comment]
Hmm, das Problem ist, wenn wir die Daten visualisieren, d.h. als COGs verfügbar machen, ist es sehr einfach, sie komplett herunterzuladen.
Einfach in den Netzwerk-Tab gehen, URL kopieren und herunterladen.
Also, was machen wir?

**Comment by cmosig** [comment]
Haha, stimmt. Hab gerade keine Minute gebraucht das zu finden. 

halb gebackene Ideen die mir einfallen:
- watermark mit dem Hinweis "not available for download". 
- die resolution vom COG nur auf 1m machen mit dem selben Hinweis 
- niemandem sagen ... :)

**Comment by JesJehle** [comment]
Das sollten wir auf jeden Fall mit Teja besprechen. Wäre schon schade, die Option viewonly nicht zu haben ..

**Comment by tejakattenborn** [comment]
Generell mit allen Antworten von Clemens (1st reply). Der Punkt mit dem view only sollte aber schon möglich sein und ist auch für das Projekt aus dem Schwarzwald zwingend erforderlich. Hier meine Idee:

Kategory "not open". Bei diesen Daten zeigen wir nur die Geolocation an als Punkt an und addieren da noch nen random Fehler von 10 km drauf.
Kategory "view only". Hier gibts einfach kein Download-Button. Wenn sich einer das Bild irgendwie hackt, dann hat er es halt. Da seh ich kein Drama. Wir haben aber vom Schwarzwald-NP das okay, dass wir die Bilder anzeigen dürfen (aber sie sollen nicht runterladbar sein). 

Okay für Euch so?

**Comment by cmosig** [comment]
@tejakattenborn das "Problem" ist das es wirklich extrem einfach ist sich die tif zu extrahieren. Es ist nur F12 -> Netzwerk Tab und dann auf den Dateinamen klicken. 

Wir haben effektiv einen offenen File Server mit den COGs und das Frontend/Visualisierung ließt daraus. 

Ich hab kein gutes Bauchgefühl damit offiziell eine view-only Variante anzubieten. Ggf dann nur für den Schwarzwald Datensatz.

**Comment by cmosig** [comment]
@JesJehle kann man eigentlich alle COGs zugreifen sobald man den Namen kennt? 

Für die privaten datasets darf das dann auf keinen Fall möglich sein. Da muss es noch ein authentication layer geben. Da hängen mehrere NDAs dran.

**Comment by tejakattenborn** [comment]
Ja, ich weiß, dass es einfach ist die Daten zu ziehen. Das war oben mit "view only" so gemeint, dass das bisher nur für den Schwarzwalddatensatz in Frage kommt. Mit anderen Daten würde ich das NICHT machen :-)

**Comment by mmaelicke** [comment]
kurz meine 50cent:
Ich glaube die grundsätzliche Frage ist hier: Sollen die Schwarzwalddaten nicht technisch nicht runterladbar sein, weil die Daten nicht 'geleakt' werden dürfen, oder soll man sie nur nicht runterladen *dürfen*. Denn am Ende des Tages darf man bilder auf einer Webseite nur für den privaten gebrauch runterladen. Wenn wir also auch nochmal klar darauf hinweisen (evtl. mit watermark), dass diese Daten nicht runtergeladen werden dürfen sind wir meines Erachtens 'rechtlich' auf der sicheren Seite. vgl. hier seiten wie shutterstock, da kann ich alles sehr einfach laden, aber ich darfs nicht. die erkennen ihre unbezahlten daten wieder und schicken dir ne abmahnung wenn du es trotzdem machst. Watermarks können übrigens sichtbar oder unsichtbar sein...

Die privaten Daten nur über authentication zu laden, da müssen wir noch ein wenig rumprobieren, wie sich das sinnvoll realisieren lässt, denn dieser prozess wird das laden der Daten deutlich behindern und im vergleich zu den offenen daten  langsamer sein.

**Comment by tejakattenborn** [comment]
Genau, die Schwarzwalddaten "dürfen" nicht runtergeladen werden. Wenn es jemand sich da durchhackt dann ist das nicht unser Bier. Watermark ist eine gute Idee. Aber ihr braucht da auch keinen großen Aufwand machen wenn das umständlich ist. hauptsache da ist kein Download-Button :-) bzw. ausgegraut.

**Comment by JesJehle** [comment]
Also gilt das dann auch für alle weiteren viewonly Daten?

**Comment by tejakattenborn** [comment]
Nein; nur Schwarzwald weil es Projektbezogen ist. Sonst würde ich glaube ich garkein View-Only machen.

**Comment by JesJehle** [comment]
> @JesJehle kann man eigentlich alle COGs zugreifen sobald man den Namen kennt?
> 
> Für die privaten datasets darf das dann auf keinen Fall möglich sein. Da muss es noch ein authentication layer geben. Da hängen mehrere NDAs dran.

Nur wenn sie über einen fileserver offen bereitgestellt werden. Das ist mit dem `cogs` Ordner der Fall. 
Wenn wir die privaten Daten auch irgendwie für eine bestimmte Nutzergruppe visualisieren wollen, müssen wir das über einen zusätzlichen Autorisierung-Layer mit einem Proxyserver oder so was machen.

**Comment by JesJehle** [comment]
> Nein; nur Schwarzwald weil es Projektbezogen ist. Sonst würde ich glaube ich garkein View-Only machen.

Ok, aber dann würde ich die Option weglassen und nur public und private anbieten, oder?

**Comment by cmosig** [comment]
> > Nein; nur Schwarzwald weil es Projektbezogen ist. Sonst würde ich glaube ich garkein View-Only machen.
> 
> Ok, aber dann würde ich die Option weglassen und nur public und private anbieten, oder?

Klingt gut :+1: 

Aber private muss wirklich private sein, s.o. :)

**Comment by JesJehle** [comment]
#83

**Comment by cmosig** [comment]
@JesJehle 

bzgl private data auf der Website. Ist da noch eine Änderung in Planung oder im fertigen Zustand?

Auf private Daten kann man im Moment einfach direkt über den link zugreifen. Da es ja einfach eine fortlaufende ID ist, ist das ein recht großer security leak. Das imo zu unsicher. Manche Kollegen haben uns Daten sogar Passwordgeschützt geschickt weil da wohl viel dranhängt das die nicht öffentlicht werden.

E.g.: https://deadtrees.earth/dataset/3713
