### ISSUE TITLE
Replacing OSM / overpass with something more reliable.

### ISSUE THREAD

**Issue by JesJehle** [Deadwood-ai/deadwood-api#92]
with the overpass api / OSM data, we have several issues:
* no data, no lower admin levels can be found
* no English name for the admin level can be found.
<img width="880" alt="image" src="https://github.com/user-attachments/assets/5fc6fe89-5483-47c9-9a84-358317d58dac">

This is a problem, particularly if we are planing to name the files based on admin levels as discusses in #56 
To fix this, I think we have several options:
* using GADM: is quite heavy, but free and scalable
* use a different provider, for example [OpenCageData](https://opencagedata.com/) (2500 requests per day are free)

I would vote for OpenCageData since it's super simple to implement, and I think 2500 requests per day is more than enough for our purposes. Also, this needs to be implemented on the storage server, so using as little resources as possible is best.

@cmosig @mmaelicke what do you think?

**Comment by cmosig** [comment]
> using GADM: is quite heavy, but free and scalable

How difficult would it be to build a service that keeps the 2.5GB table in memory? 

Claude suggests this: looks simple, but yet another thing to maintain for you. 
![image](https://github.com/user-attachments/assets/a61bcd45-36c0-4b4b-b3c2-b9980edac102)


> OpenCageData

This seems to make a lot of sense. But the free-tier is technically only for testing. I hope this does not backfire and we get licensing issues. From their website: 
![image](https://github.com/user-attachments/assets/e8c7c2cf-6d7f-4bf3-a0c0-b274b9e3e38e)

**Comment by JesJehle** [comment]
hmm, yes this is valid.

**Comment by mmaelicke** [comment]
Hi,

just as a quick note: 2.5GB in memory is nothing we should do on the storage-server. However, I am not sure, why this should be necessary. I am not familiar with GADM in depth, but if it comes as sqlite, we can have a sqlite database on the storage-server and simply query it. Its size does not really matter (only the index needs to fit into memory to be fast).

I don't know OpenCageData, but in the setting we have, I would prefer the local solution, as it is less error prone.

**Comment by mmaelicke** [comment]
and as another note: We specifically chose the levels in a way that the coarser one is always available and at least one of the others. So can you confirm, that some labels we thought should always be there are missing?

For the translation: Most labels come in a localization flavor. I guess a *labelname*:en should be available for this stuff. 
However, I am not sure how complicated it is, to debug that stuff
